Add solution to Assignment 3
elifguler96/CodeU-2017 pull request #4
Opened 2017-06-11 21:13 UTC by elifguler96

2017-06-13 09:33 UTC, katermar commented
Please comment your code

2017-06-13 10:34 UTC, elifguler96 commented
You are right, I forgot 😅 I'll add the comments tonight 👍🏻 Thanks for the catch

2017-06-13 12:55 UTC, elifguler96 commented
I added the comments 😃

2017-06-13 22:10 UTC, katermar reviewed
Thanks for adding comments, you've made it easier to understand. I've left a few comments, but almost everything looks nice for me.

2017-06-13 22:10 UTC, katermar commented on Assignment3.java
> +        if (!dictionary.isPrefix(s + grid[row][column])) {
Where is your class "MyDictionary"? Or it is supposed that it is given? How does the test acts without list of prefixes and list of words?

2017-06-13 22:10 UTC, katermar commented on Assignment3.java
> +        if (dictionary.isWord(s)) {
The same issue as higher mentioned
Or maybe you can add some comments 
(So, you need to add comments)

2017-06-13 22:10 UTC, katermar commented on Assignment3.java
>          return words;
you can reduce this part of code just writing `return new ArrayList<String>(setOfWords);`

2017-06-13 22:10 UTC, katermar commented on Assignment3.java
>  public class Assignment3 {
maybe I'm not right? but isn't it better to name your class smth like `WordsGridFinder` ? To make it more understandable .

2017-06-14 07:11 UTC, elifguler96 commented on Assignment3.java
>  public class Assignment3 {
Yeah it is, but I just name all the assignments with their numbers, I made it sort of a convention :D

2017-06-14 07:16 UTC, elifguler96 commented on Assignment3.java
>          return words;
Thanks 👍

2017-06-14 07:22 UTC, elifguler96 commented on Assignment3.java
> +        if (!dictionary.isPrefix(s + grid[row][column])) {
I have the Dictionary class, but as one of the mentors said in the slack channel and during the Hangout, I just used it for testing, I didn't submit the file.

![screen shot 2017-06-14 at 10 21 25 am](https://user-images.githubusercontent.com/17977547/27120181-47a2cbfc-50eb-11e7-944c-d83810a8aca4.png)

2017-06-14 07:24 UTC, elifguler96 commented on Assignment3.java
> +        if (!dictionary.isPrefix(s + grid[row][column])) {
Don't think of this as a Java file that is going to compile. Just think of it as you wrote this code in Google Docs, like in the interview. In the pdf, it says that the dictionary and its methods are given.

2017-06-14 07:27 UTC, katermar commented on Assignment3.java
>  public class Assignment3 {
Yeah, I've noticed that :)

2017-06-14 07:30 UTC, katermar commented on Assignment3.java
> +        if (!dictionary.isPrefix(s + grid[row][column])) {
Oh, okay, I'm just curious how does your test without any prefix list and word list act :)

2017-06-14 07:34 UTC, elifguler96 commented on Assignment3.java
> +        if (!dictionary.isPrefix(s + grid[row][column])) {
Of course, if you try to run the tests right now, it won't even compile. I run the tests with `MyDictionary` class and then submitted my code here.

2017-06-15 17:09 UTC, brzozan requested changes
Very good! Only a few comments.

2017-06-15 17:09 UTC, brzozan commented on Assignment3.java
> +import java.util.*;
Importing contents of whole package via * is generally discouraged. It pollutes local namespace and makes it non-obvious which classes are expected to be used.

See for example longer explanations on [Stack Overflow](https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad).

2017-06-15 17:09 UTC, brzozan commented on Assignment3.java
> +    private Set<String> setOfWords = new HashSet<>();
It would be a bit better from design perspective to pass this set as a parameter to the methods, so that instances of class Assignment3 are stateless. Currently if you call findAllWords twice with different grids, you will get incorrect result from the second call - list will contain words from both first and second grid, since first invocation changes the state of the object and modifies its behavior for future calls.

Managing state can be a source of serious and difficult to find bugs, that happen only after a specific sequence of events happens. A simple example for this case is shown above.
Storing state in the object should have good reason, for example caching of generated results so that the next invocation with the same parameters returns cached result rather than generate new one.

2017-06-15 17:09 UTC, brzozan commented on Assignment3Test.java
> +import static org.junit.jupiter.api.Assertions.*;
Importing lots of stuff just to use a single assertEquals :(

2017-06-15 17:09 UTC, brzozan commented on Assignment3Test.java
> +        assertEquals(new HashSet<>(new Assignment3().findAllWords(2, 3, grid, new MyDictionary())),
Usual practice is to create tested object in a separate method annotated with `@Before` and only use it in test.

Also: clever use of wrapping in HashSets to work around changing order of elements! There are nice [libraries](https://google.github.io/truth/) that let you handle it in a cleaner way[1], but feel free to leave it as is to not overcomplicate things.

[1] `assertThat(result).containsExactly(s1, s2, s3);`

2017-06-15 17:09 UTC, brzozan commented on Assignment3Test.java
> +class Assignment3Test {
Any tests for edge cases, like empty grid or grid with no words from dictionary?

2017-06-15 17:09 UTC, brzozan commented on Assignment3.java
> +                                                   MyDictionary dictionary) {
A minor thing, but makes code difficult to read: line with MyDictionary is indented waaaaaaaaaaaay too far.

2017-06-15 20:13 UTC, elifguler96 commented on Assignment3.java
> +import java.util.*;
IntelliJ did that automatically I guess 😅

2017-06-15 20:21 UTC, elifguler96 commented on Assignment3Test.java
> +        assertEquals(new HashSet<>(new Assignment3().findAllWords(2, 3, grid, new MyDictionary())),
I searched for that but couldn't find it, thanks 😄

2017-06-23 16:25 UTC, brzozan approved these changes
LGTM

2017-06-23 17:22 UTC, merged